Algoritmo sin_titulo
	ESCRIBIR "BUSCA LA RAIZ DEL NUMERO"
	LEER A
	DATO = A
	//DATORAIZ = RC (DATO)
	ESCRIBIR "EL DATO ES, ", DATO
	ESCRIBIR "SU RAIZ ES, ", RC(DATO) 
	DATO2= RC(DATO)
	ESCRIBIR "LA PARTE ENTERA DE DATO, " TRUNC(A)
	ESCRIBIR "REDONDEANDO LA RAIZ, " REDON(DATO2)
	DATO3= REDON(DATO2)
	ESCRIBIR "NUMERO AL AZAR DEL RENDONDEO, " AZAR(DATO3)
	
	ESCRIBIR "CONCATENO, " DATO + DATO3
	
	
	
	
	
FinAlgoritmo
